# Generated by Django 3.2.9 on 2022-02-16 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugrecue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickandfleatreatment', models.BooleanField(default=True)),
                ('towelandblowdry', models.BooleanField(default=True)),
                ('perfumesparay', models.BooleanField(default=True)),
                ('deshedding', models.BooleanField(default=True)),
                ('nailtrimming', models.BooleanField(default=True)),
                ('earcleaning', models.BooleanField(default=True)),
                ('theethcleaning', models.BooleanField(default=True)),
                ('pawmassage', models.BooleanField(default=True)),
                ('medicatedbath', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField()),
                ('discountprice', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Bugrecue',
            },
        ),
        migrations.CreateModel(
            name='Groomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Happyandshiny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathandShampoo', models.BooleanField(default=True)),
                ('towelandblowdry', models.BooleanField(default=True)),
                ('perfumesparay', models.BooleanField(default=True)),
                ('deshedding', models.BooleanField(default=True)),
                ('nailtrimming', models.BooleanField(default=True)),
                ('earcleaning', models.BooleanField(default=True)),
                ('theethcleaning', models.BooleanField(default=True)),
                ('pawmassage', models.BooleanField(default=True)),
                ('Hairtrimiming', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField()),
                ('discountprice', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'happyandshiny',
            },
        ),
        migrations.CreateModel(
            name='Hygienicpamper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathandShampoo', models.BooleanField(default=True)),
                ('towelandblowdry', models.BooleanField(default=True)),
                ('perfumesparay', models.BooleanField(default=True)),
                ('deshedding', models.BooleanField(default=True)),
                ('nailtrimming', models.BooleanField(default=True)),
                ('earcleaning', models.BooleanField(default=True)),
                ('theethcleaning', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField()),
                ('discountprice', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Hygienicpamper',
            },
        ),
        migrations.CreateModel(
            name='Shinyandbugfree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='', max_length=200, null=True)),
                ('bathandShampoo', models.BooleanField(default=True)),
                ('perfumesparay', models.BooleanField(default=True)),
                ('towelandblowdry', models.BooleanField(default=True)),
                ('deshedding', models.BooleanField(default=True)),
                ('nailtrimming', models.BooleanField(default=True)),
                ('earcleaning', models.BooleanField(default=True)),
                ('theethcleaning', models.BooleanField(default=True)),
                ('pawmassage', models.BooleanField(default=True)),
                ('Hairtrimiming', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField(verbose_name='Shinyandbugfree price')),
            ],
            options={
                'db_table': 'shinyandbugfree',
            },
        ),
        migrations.CreateModel(
            name='GroomerBookingslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=25, null=True)),
                ('last_name', models.CharField(default='', max_length=10, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_no', models.CharField(default='', max_length=12, null=True)),
                ('date', models.DateField(help_text='DD-MM-YYYY')),
                ('timeslot', models.IntegerField(choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30'), (6, '15:00 – 15:30'), (7, '16:00 – 16:30'), (8, '17:00 – 17:30')])),
                ('patient_name', models.CharField(max_length=60)),
                ('petname', models.CharField(choices=[('D', 'Dog'), ('C', 'Cat'), ('O', 'Other')], default='', max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=9)),
                ('message', models.CharField(default='', max_length=255, null=True)),
                ('groomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grooming.groomer')),
            ],
            options={
                'unique_together': {('groomer', 'date', 'timeslot')},
            },
        ),
    ]
