# Generated by Django 3.2.9 on 2022-03-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=25, null=True)),
                ('last_name', models.CharField(default='', max_length=10, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_no', models.CharField(default='', max_length=12, null=True)),
                ('date', models.DateField(help_text='DD-MM-YYYY')),
                ('timeslot', models.IntegerField(choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30'), (6, '15:00 – 15:30'), (7, '16:00 – 16:30'), (8, '17:00 – 17:30')])),
                ('boarding', models.CharField(choices=[('Dog Boarding', 'Dog Boarding'), ('Dog Kennels', 'Dog Kennels'), ('Cat Boarding', 'Cat Boarding'), ('Doggy Daycare', 'Doggy Daycare'), ('Pet Hotels', 'Pet Hotels'), ('Private Pet Boarding', 'Private Pet Boarding')], default='', max_length=60)),
                ('message', models.CharField(default='', max_length=255, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'date', 'timeslot')},
            },
        ),
    ]
