# Generated by Django 3.2.9 on 2022-03-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qunitity',
            new_name='quantity',
        ),
    ]
